### ISSUE TITLE
Requirements (Code Generator)

### ISSUE THREAD

**Issue by garylyp** [garylyp/compiler#3]
# Code Generator
- [x] Translate IR3 (intermediate representation from Part 2) to ARM assembly code
- [x] Register allocation 
  - [x] Offsets for variable access
  - [x] Smart algorithms for register allocation and assignment.
  - [x] Flag to enable or disable optimizations (DEFAULT should be **DISABLED**)

The effectiveness of register allocation is accessed, but it carries a lower weight.

Bonus
- [x] Optimizations

Not Required
- Integer division
- `readln` or `println` with objects as arguments
- read strings
- string concatenation

Should Support
- Reading integers (`scanf`) 
- Printing integers and strings (`printf`)
- `malloc(size_in_bytes)` to create new objects
- `free` if possible

# Report
- [x] Report describing front-end, middle-end and back-end
  - [x] front-end
  - [x] middle-end
  - [x] back-end 
- [x] Optimizations
- [x] Register Allocation
- [x] Challenges

# Subtasks
- [x] Memory management for function calls
- [x] Register Allocation and Management
- [x] Register live range
- [x] GETREG
- [x] get rekt

Things to handle
- [x] Local variables
- [x] Print, Read
- [x] Return
- [x] Objects and field variables
- [x] Assignment
- [x] Calls
- [x] goto

**Comment by garylyp** [comment]
Previously Existing Optimizations for IR3
1. 

Additional Work for IR3 (intermediate code generator)
1. Collapse adjacent labels
2. Remove Labels that is at the end of the method body
3. Collapse if-goto and goto statements if they are adjacent and goto the same label
4. High-level deadcode elimination: remove lines after goto until the next label or end-of-method is reached

**Comment by garylyp** [comment]
Symbol Table
1. Populated with all class info (the fields of each class and their offsets, the total size required if object needs to be malloc on heap)
2. Populated with all var info to easily check the type of each var
3. Populated with all method info so that function invocation information is known before each function invocation
  i. Additional stack space required 
  ii. Mapping of variables to stack offset
  iii. Number of v registers needed so that it can be spilled on stack

**Comment by garylyp** [comment]
Handling String Literals
* All string literals that are used will be stored in `.data`. If they need to be used, their memory location is retrieved by their specific offset
* All format specifiers `%d`. `%d\n`, %s\n` are also stored in the data to enable easier calling of `scanf` and `printf` which uses these specifiers as their first argument
* A null string `""` is also stored in the data segment. All initialized string vars and fields will take on this value if unspecified

Return
* Simply place result in a1

**Comment by garylyp** [comment]
Possible optimization
* For IR3, if the result of if conditional can be resolved directly (i.e. _e1 == _e1 or (3  >= 2), change it to a `goto` statement instead

**Comment by garylyp** [comment]
Because a1 gets updated after the function call, the initial value of a1 is stored to stack, and restored after the function call

**Comment by garylyp** [comment]
Use relative addressing for:
* Accessing arguments that did not fit into a1-a4 e.g. add(1,2,3,4,5,6,7), then 5, 6 and 7 are stored on m4, m5 and m6 respectively
* Store values of a1 and a4 before function calls so that they can be restored after returning from function call (4 slots of 4 bytes each are reserved on the stack for this purpose)


The following show how the stack was managed for my implementation
* The stack grows downwards (to smaller addresses)
* The frame pointer always points to the base of the stack and is most frequently used to retrieve data from the stack for the current activation frame
* The stack pointer is at the top of the stack and is used to prepare the stack for the next function invocation (store overflowing arguments on the stack for the next function call, then incremented before stmfd is invoked)
![image](https://user-images.githubusercontent.com/41105221/142220888-dc1351a2-8e30-4ce3-82df-18519a6ec6b5.png)
